### ISSUE TITLE
ACPI (PCI/E820 conflict) error when booting Windows on Sandy/Ivy bridge and Bay-trail chromebook

### ISSUE THREAD

**Issue by coolstar** [KevinOConnor/seabios#2]
When booting Windows on Sandy/Ivy bridge and Bay-trail chromebook, there's an ACPI error.

This is the error that is reported by Windows:
"The list of resources that PCI claims to decode overlaps with the list of memory regions that the E820 BIOS interface reports."

**Comment by KevinOConnor** [comment]
Please report issues with SeaBIOS to the mailing list as described at: http://www.seabios.org/Debugging#Trouble_reporting .  FWIW, SeaBIOS obtains acpi tables from coreboot and so this is likely something that needs to be reported to the coreboot list.
